### ISSUE TITLE
Never more than 1 child?

### ISSUE THREAD

**Issue by bwoogie** [wackoisgod/ValTreeCSharp#1]
I never get more than 1 child returned.

> tiles
> (tab) tile
> (tab)(tab)        x 32
> (tab)(tab)        y 16

tile should have 2 children, but it only returns x. x has 1 sibling.
Is that how it's supposed to work?

**Comment by wackoisgod** [comment]
Hey bwoogie, 

So I have gone ahead and update the class to be more inline with the C++ version and it should properly work now and return back the proper amount of children for a given tree. 

I have also added support for things that were not functioning correctly before, like iterating over a ValTree object etc.. and not properly supporting comments like the c++ version has.

I also added a test project with the same proper test to make sure stuff is working.
